import GAME_SETTINGS from "../constants/gameSettings.js";
import LOCAL_STORAGE_KEYS from "../constants/localStorageKeys.js";

export default {
    addPoint: function (numberOfPoints = 1) {
        GAME_SETTINGS.RECORD += numberOfPoints;

        this.verifyCurrentScore();
    },
    verifyCurrentScore: function() {
        if (GAME_SETTINGS.RECORD <= GAME_SETTINGS.FIFTH_RECORD) return;

        else if(GAME_SETTINGS.RECORD > GAME_SETTINGS.FIRST_RECORD)
        {
            GAME_SETTINGS.FIFTH_RECORD = GAME_SETTINGS.FORTH_RECORD;
            GAME_SETTINGS.FORTH_RECORD = GAME_SETTINGS.THIRD_RECORD;
            GAME_SETTINGS.THIRD_RECORD = GAME_SETTINGS.SECOND_RECORD;
            GAME_SETTINGS.SECOND_RECORD = GAME_SETTINGS.FIRST_RECORD;
            GAME_SETTINGS.FIRST_RECORD = GAME_SETTINGS.RECORD;
        }
        else if(GAME_SETTINGS.RECORD > GAME_SETTINGS.SECOND_RECORD)
        {
            GAME_SETTINGS.FIFTH_RECORD = GAME_SETTINGS.FORTH_RECORD;
            GAME_SETTINGS.FORTH_RECORD = GAME_SETTINGS.THIRD_RECORD;
            GAME_SETTINGS.THIRD_RECORD = GAME_SETTINGS.SECOND_RECORD;
            GAME_SETTINGS.SECOND_RECORD = GAME_SETTINGS.RECORD;
        }
        else if(GAME_SETTINGS.RECORD > GAME_SETTINGS.THIRD_RECORD)
        {
            GAME_SETTINGS.FIFTH_RECORD = GAME_SETTINGS.FORTH_RECORD;
            GAME_SETTINGS.FORTH_RECORD = GAME_SETTINGS.THIRD_RECORD;
            GAME_SETTINGS.THIRD_RECORD =  GAME_SETTINGS.RECORD;
        }
        else if(GAME_SETTINGS.RECORD > GAME_SETTINGS.FORTH_RECORD)
        {
            GAME_SETTINGS.FIFTH_RECORD = GAME_SETTINGS.FORTH_RECORD;
            GAME_SETTINGS.FORTH_RECORD = GAME_SETTINGS.RECORD;
        }
        else if(GAME_SETTINGS.RECORD > GAME_SETTINGS.FIFTH_RECORD)
        {
            GAME_SETTINGS.FIFTH_RECORD = GAME_SETTINGS.RECORD;
        }
        
        localStorage.setItem(
            LOCAL_STORAGE_KEYS.RECORD,
            GAME_SETTINGS.RECORD
        );
    }
};